name: Catch2

on:
	push:
		branches: [ "master" ]

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v3
		- name: build
			run: make

	test:
		needs: build
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v3
		- name: build
			run: make
		- name: test
			run: make build
			run: make test
