name: Catch2

on:
  push:
    branches: [ "master" ]

jobs:
  vector:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test TESTFILES=vector.cpp
    - run: make bm
    - run: ./bm vector
  stack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test TESTFILES=stack.cpp
    - run: make bm
    - run: ./bm stack
  map:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test TESTFILES=map.cpp
    - run: make bm
    - run: ./bm map
  set:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test TESTFILES=set.cpp
    - run: make bm
    - run: ./bm set
