name: Catch2

on:
  push:
    branches: [ "master" ]

jobs:
  vector:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test CASE=vector
  stack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test CASE=stack
  map:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test CASE=map
  set:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test CASE=set
  benchmark:
    needs: [vector, stack, map, set]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make bm
